SELECT 
    C.CAR_ID,
    C.CAR_TYPE,
    ROUND(C.DAILY_FEE*30*(1-(D.DISCOUNT_RATE/100))) AS FEE
    
FROM CAR_RENTAL_COMPANY_CAR AS C
JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY AS H
ON C.CAR_ID = H.CAR_ID

JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN AS D
ON C.CAR_TYPE = D.CAR_TYPE

WHERE C.CAR_TYPE IN ('세단', 'SUV')
AND DURATION_TYPE LIKE '30%'
AND ROUND(C.DAILY_FEE*30*(1-(D.DISCOUNT_RATE/100))) BETWEEN 500000 AND 1999999
AND C.CAR_ID NOT IN (SELECT CAR_ID
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
            WHERE START_DATE < '2022-12-01' AND END_DATE >= '2022-11-01')
GROUP BY CAR_ID;