SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT(S.USER_ID)) AS PUCHASED_USERS,
    ROUND(
        (COUNT(DISTINCT(S.USER_ID))) / 
        (SELECT 
            COUNT(DISTINCT(USER_INFO.USER_ID)) 
         FROM USER_INFO 
         WHERE JOINED LIKE '2021%')
        ,1) AS PUCHASED_RATIO
        
FROM ONLINE_SALE AS S
INNER JOIN
        (
            SELECT *
            FROM USER_INFO
            WHERE JOINED LIKE '2021%'
        ) AS U
        ON U.USER_ID = S.USER_ID

GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;