SELECT
    R.MEMBER_NAME,
    O.REVIEW_TEXT,
    DATE_FORMAT(O.REVIEW_DATE,'%Y-%m-%d') AS REVIEW_DATE
FROM REST_REVIEW AS O
JOIN(
    SELECT 
        A.MEMBER_ID,
        B.MEMBER_NAME,
        RANK() OVER(ORDER BY CNT DESC) AS RANKING
    FROM (
        SELECT *, COUNT(MEMBER_ID) AS CNT
        FROM REST_REVIEW
        GROUP BY MEMBER_ID) AS A
    JOIN MEMBER_PROFILE AS B
    ON A.MEMBER_ID = B.MEMBER_ID
    ) AS R
ON O.MEMBER_ID = R.MEMBER_ID
WHERE R.RANKING = 1
ORDER BY O.REVIEW_DATE;